apiVersion: "v1"
name: cluster-api-core
description: "Helm chart for cluster api core."
home: "https://github.com/giantswarm/cluster-api-core-app"
version: "[[ .Version ]]"
appVersion: [[ .AppVersion ]]
annotations:
  application.giantswarm.io/owners: |
    - catalog: default
      provider: aws
      team: firecracker
    - catalog: default
      provider: azure
      team: celestial
  config.giantswarm.io/version: "capi-v0.4.0-beta.1"
