apiVersion: "v1"
name: cluster-api-core
description: "Helm chart for cluster api core."
home: "https://github.com/giantswarm/cluster-api-core-app"
version: "[[ .Version ]]"
appVersion: 0.3.19-gs1
annotations:
  application.giantswarm.io/owners: |
    - catalog: default
      provider: aws
      team: firecracker
    - catalog: default
      provider: azure
      team: celestial
