name: cluster-api-core

images:
  controller:
    name: giantswarm/cluster-api-controller
    tag: 815685c3d03ac5ca7b6eed6c3a3e3aafd0b96ad9
  proxy:
    name: giantswarm/kube-rbac-proxy
    tag: v0.8.0

crdConvertOnly: true

featuregates:
  machinepool: true
  clusterresourceset: true

ports:
  proxy: 8443
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
