name: cluster-api-core

images:
  controller:
    registry: quay.io
    name: giantswarm/cluster-api-controller
    tag: 7c147a93ef43d5ffa0070c77c37da1fed456f000
  proxy:
    registry: gcr.io
    name: kubebuilder/kube-rbac-proxy
    tag: v0.8.0

crdConvertOnly: true

featuregates:
  machinepool: true
  clusterresourceset: true

ports:
  proxy: 8443
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
