name: cluster-api-core

images:
  controller:
    name: giantswarm/cluster-api-controller
    tag: 98fc14614970fe9d4542cb6173061290b3e765db

crdConvertOnly: true

featuregates:
  machinepool: true
  clusterresourceset: true

ports:
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi
