name: cluster-api-core

registry:
  domain: quay.io

image:
  name: giantswarm/cluster-api-controller
  tag: v0.4.0

featuregates:
  machinepool: true
  clusterresourceset: true

ports:
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi
