name: cluster-api-core
image:
  registry: quay.io
  name: giantswarm/cluster-api-controller
  tag: 5d947a4af1718936f5fbefd7cc7e4e5a32b234a7

featuregates:
  machinepool: true
  clusterresourceset: false

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
