name: cluster-api-core
image:
  registry: quay.io
  name: giantswarm/cluster-api-controller
  tag: 66166e390b53803512ddbe95054cadfe553ad186

featuregates:
  machinepool: true
  clusterresourceset: false

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
