name: cluster-api-core

images:
  controller:
    registry: quay.io
    name: giantswarm/cluster-api-controller
    tag: c99d25fc6ab069f35c28387e45a8ce0c57623729
  proxy:
    registry: gcr.io
    name: kubebuilder/kube-rbac-proxy
    tag: v0.8.0

featuregates:
  machinepool: true
  clusterresourceset: true

ports:
  proxy: 8443
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
