name: cluster-api-core
image:
  registry: quay.io
  name: giantswarm/cluster-api-controller
  tag: c3bfae085ccb9781792bcf89f2e5c1d4b0078266

featuregates:
  machinepool: true
  clusterresourceset: false

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
