name: cluster-api-core
image:
  registry: quay.io
  name: giantswarm/cluster-api-controller
  tag: 0cece0b23afabd4918d1f619e7557c8221a1ed24

featuregates:
  machinepool: true
  clusterresourceset: false

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
