name: cluster-api-core
image:
  registry: quay.io
  name: giantswarm/cluster-api-controller
  tag: 7c147a93ef43d5ffa0070c77c37da1fed456f000

featuregates:
  machinepool: true
  clusterresourceset: false

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
