apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    giantswarm.io/monitoring: "true"
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: https
    port: {{ .values.ports.proxy }}
    targetPort: https
  selector:
    {{- include "labels.selector" . | nindent 4 }}
