apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.webhook.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
      control-plane: webhook
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
        control-plane: webhook
    spec:
      containers:
      - args:
        - --metrics-addr=0.0.0.0:{{ .Values.ports.metrics }}
        - --webhook-port={{ .Values.ports.webhook }}
        - --feature-gates=MachinePool={{ .Values.featuregates.machinepool }},ClusterResourceSet={{ .Values.featuregates.clusterresourceset }}
        command:
        - /manager
        image: "{{ .Values.registry.domain }}/{{ .Values.images.controller.name }}:{{ .Values.images.controller.tag }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
        name: manager
        ports:
        - containerPort: {{ .Values.ports.healthz }}
          name: healthz
          protocol: TCP
        - containerPort: {{ .Values.ports.webhook }}
          name: webhook
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ include "resource.webhook.name"  . }}
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "resource.webhook.name"  . }}
