apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    giantswarm.io/monitoring: "true"
    giantswarm.io/monitoring-port: "{{ .Values.ports.metrics }}"
  name: {{ include "resource.webhook.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: webhook
    port: {{ .Values.ports.webhook }}
    targetPort: webhook
  - name: metrics
    port: {{ .Values.ports.metrics }}
    targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
    control-plane: webhook
